# Generated by Django 3.0.7 on 2020-06-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200627_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.Book'),
        ),
    ]
